# Generated by Copilot
"""
Main CLI entry point for Custom Rules
"""
import click
from rich.console import Console
from rich.table import Table
import sys
import os
from pathlib import Path

from ..core.config import ConfigManager
from .commands.init import init_command
from .commands.profile import profile_group
from .commands.run import run_command
from .commands.report import report_command
from .commands.validate import validate_command

console = Console()

@click.group()
@click.option('--profile', '-p', 
              help='Configuration profile to use',
              type=str,
              default=None)
@click.option('--dest', '-d', 
              help='Destination directory for outputs',
              type=click.Path(exists=False, file_okay=False, dir_okay=True, path_type=Path),
              default=None)
@click.option('--verbose', '-v', 
              is_flag=True,
              help='Enable verbose logging')
@click.option('--config', '-c',
              help='Path to configuration file',
              type=click.Path(exists=True, dir_okay=False, path_type=Path),
              default=None)
@click.version_option(version='1.0.0', prog_name='custom-rules')
@click.pass_context
def cli(ctx, profile, dest, verbose, config):
    """
    Custom Rules CLI - A customizable tool for project rules validation and enforcement
    
    Use --profile to specify which configuration profile to use.
    Use --dest to specify where outputs should be written.
    Use --verbose for detailed logging output.
    """
    # Ensure context object exists
    ctx.ensure_object(dict)
    
    # Store global options in context
    ctx.obj['profile'] = profile
    ctx.obj['dest'] = dest
    ctx.obj['verbose'] = verbose
    ctx.obj['config'] = config
    
    # Initialize configuration manager
    try:
        config_manager = ConfigManager(
            profile_name=profile,
            config_file=config,
            verbose=verbose
        )
        ctx.obj['config_manager'] = config_manager
    except Exception as e:
        if verbose:
            console.print(f"[red]Error initializing configuration: {e}[/red]")
        ctx.obj['config_manager'] = None

# Add command groups and commands
cli.add_command(init_command, name='init')
cli.add_command(profile_group, name='profile') 
cli.add_command(run_command, name='run')
cli.add_command(report_command, name='report')
cli.add_command(validate_command, name='validate')

@cli.command()
@click.pass_context
def version(ctx):
    """Show version information"""
    console.print(f"[bold blue]Custom Rules CLI[/bold blue] version [green]1.0.0[/green]")
    
    if ctx.obj.get('verbose'):
        console.print(f"Python: {sys.version}")
        console.print(f"Platform: {sys.platform}")

@cli.command()
@click.pass_context 
def info(ctx):
    """Show current configuration and status"""
    config_manager = ctx.obj.get('config_manager')
    
    table = Table(title="Custom Rules CLI Information")
    table.add_column("Setting", style="cyan")
    table.add_column("Value", style="green")
    
    table.add_row("Version", "1.0.0")
    table.add_row("Profile", ctx.obj.get('profile') or 'default')
    table.add_row("Destination", str(ctx.obj.get('dest') or 'current directory'))
    table.add_row("Verbose", str(ctx.obj.get('verbose')))
    table.add_row("Config File", str(ctx.obj.get('config') or 'auto-detected'))
    
    if config_manager:
        table.add_row("Config Status", "[green]Loaded[/green]")
    else:
        table.add_row("Config Status", "[yellow]Not loaded[/yellow]")
    
    console.print(table)

def main():
    """Main entry point"""
    try:
        cli()
    except KeyboardInterrupt:
        console.print("\n[yellow]Operation cancelled by user[/yellow]")
        sys.exit(1)
    except Exception as e:
        console.print(f"[red]Unexpected error: {e}[/red]")
        sys.exit(1)

if __name__ == '__main__':
    main()
