# Generated by Copilot
"""
Configuration management for Custom Rules CLI
"""
import yaml
import os
from pathlib import Path
from typing import Dict, Any, Optional
from rich.console import Console

console = Console()

class ConfigManager:
    """Manages configuration loading and validation"""
    
    def __init__(self, profile_name: Optional[str] = None, 
                 config_file: Optional[Path] = None,
                 verbose: bool = False):
        self.profile_name = profile_name or 'default'
        self.config_file = config_file
        self.verbose = verbose
        self.config = {}
        
        # Try to load configuration
        self._load_config()
    
    def _load_config(self):
        """Load configuration from file or use defaults"""
        config_paths = self._get_config_paths()
        
        for path in config_paths:
            if path.exists():
                try:
                    with open(path, 'r', encoding='utf-8') as f:
                        self.config = yaml.safe_load(f) or {}
                    
                    if self.verbose:
                        console.print(f"[green]Loaded configuration from: {path}[/green]")
                    return
                except Exception as e:
                    if self.verbose:
                        console.print(f"[yellow]Failed to load config from {path}: {e}[/yellow]")
                    continue
        
        # Use default configuration if no config file found
        self.config = self._get_default_config()
        if self.verbose:
            console.print("[yellow]Using default configuration[/yellow]")
    
    def _get_config_paths(self) -> list[Path]:
        """Get possible configuration file paths in order of preference"""
        paths = []
        
        # Explicit config file
        if self.config_file:
            paths.append(self.config_file)
        
        # Current directory
        paths.extend([
            Path.cwd() / 'custom-rules.yaml',
            Path.cwd() / 'custom-rules.yml',
            Path.cwd() / '.custom-rules.yaml',
            Path.cwd() / '.custom-rules.yml'
        ])
        
        # Profile-specific configs
        profiles_dir = Path.cwd() / 'profiles'
        if profiles_dir.exists():
            paths.extend([
                profiles_dir / f'{self.profile_name}.yaml',
                profiles_dir / f'{self.profile_name}.yml'
            ])
        
        # Home directory
        home = Path.home()
        paths.extend([
            home / '.config' / 'custom-rules' / 'config.yaml',
            home / '.custom-rules.yaml'
        ])
        
        return paths
    
    def _get_default_config(self) -> Dict[str, Any]:
        """Get default configuration"""
        return {
            'name': self.profile_name,
            'version': '1.0.0',
            'settings': {
                'output_format': 'json',
                'verbose': self.verbose,
                'max_workers': 4
            },
            'rules': [],
            'destinations': {
                'reports': './reports',
                'logs': './logs'
            },
            'integrations': {
                'git': {
                    'enabled': False
                }
            }
        }
    
    def get(self, key: str, default: Any = None) -> Any:
        """Get configuration value by key (supports dot notation)"""
        keys = key.split('.')
        value = self.config
        
        for k in keys:
            if isinstance(value, dict) and k in value:
                value = value[k]
            else:
                return default
        
        return value
    
    def set(self, key: str, value: Any):
        """Set configuration value by key (supports dot notation)"""
        keys = key.split('.')
        config = self.config
        
        for k in keys[:-1]:
            if k not in config:
                config[k] = {}
            config = config[k]
        
        config[keys[-1]] = value
    
    def save(self, path: Optional[Path] = None):
        """Save configuration to file"""
        if not path:
            path = Path.cwd() / f'{self.profile_name}.yaml'
        
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            with open(path, 'w', encoding='utf-8') as f:
                yaml.dump(self.config, f, default_flow_style=False, sort_keys=False)
            
            if self.verbose:
                console.print(f"[green]Configuration saved to: {path}[/green]")
        except Exception as e:
            console.print(f"[red]Failed to save configuration: {e}[/red]")
            raise
