# Generated by Copilot
"""
Custom Rules CLI Package
A customizable CLI tool for project rules validation and enforcement
"""

__version__ = "1.0.0"
__author__ = "tbowman01"
__description__ = "A customizable CLI tool for project rules validation and enforcement"
