# Generated by Copilot
"""
Init command for Custom Rules CLI
"""
import click
from pathlib import Path
from rich.console import Console
from rich.table import Table
from rich.prompt import Confirm

console = Console()

@click.command()
@click.option('--interactive', '-i', 
              is_flag=True,
              help='Launch interactive setup wizard')
@click.option('--force', '-f',
              is_flag=True, 
              help='Overwrite existing files without prompting')
@click.option('--dry-run', '-n',
              is_flag=True,
              help='Show what files would be created/modified without making changes')
@click.option('--merge', '-m',
              is_flag=True,
              help='Append rules to existing files instead of overwriting')
@click.option('--profile', '-p',
              help='Use specific profile for initialization')
@click.option('--dest', '-d',
              help='Destination directory for configuration files',
              type=click.Path(file_okay=False, dir_okay=True, path_type=Path))
@click.pass_context
def init_command(ctx, interactive, force, dry_run, merge, profile, dest):
    """Initialize Custom Rules configuration with advanced options"""
    
    # Use global options if local ones not provided
    global_profile = ctx.obj.get('profile')
    global_dest = ctx.obj.get('dest')
    verbose = ctx.obj.get('verbose', False)
    
    # Determine final options
    final_profile = profile or global_profile or 'default'
    final_dest = Path(dest or global_dest or Path.cwd())
    
    if verbose:
        console.print(f"[blue]Initializing with profile: {final_profile}[/blue]")
        console.print(f"[blue]Destination: {final_dest}[/blue]")
    
    # Show current options
    if verbose or dry_run:
        table = Table(title="Initialization Options")
        table.add_column("Option", style="cyan")
        table.add_column("Value", style="green")
        
        table.add_row("Profile", final_profile)
        table.add_row("Destination", str(final_dest))
        table.add_row("Interactive", str(interactive))
        table.add_row("Force", str(force))
        table.add_row("Dry Run", str(dry_run))
        table.add_row("Merge", str(merge))
        
        console.print(table)
    
    try:
        # Analyze existing files and conflicts
        conflicts = analyze_existing_files(final_dest, final_profile)
        
        if dry_run:
            preview_operations(conflicts, merge, force, final_dest, final_profile)
            return
        
        if interactive:
            run_interactive_setup(final_dest, final_profile, force, merge)
        else:
            run_standard_init(conflicts, force, merge, final_dest, final_profile)
            
        console.print("[green]✓ Initialization completed successfully![/green]")
        
    except Exception as e:
        console.print(f"[red]Error during initialization: {e}[/red]")
        raise click.ClickException(f"Initialization failed: {e}")

def analyze_existing_files(dest_path: Path, profile: str) -> dict:
    """Analyze existing files and detect conflicts"""
    conflicts = {
        'config_files': [],
        'profile_files': [],
        'other_files': []
    }
    
    # Check for main config files
    config_files = [
        'custom-rules.yaml',
        'custom-rules.yml',
        '.custom-rules.yaml',
        '.custom-rules.yml'
    ]
    
    for config_file in config_files:
        file_path = dest_path / config_file
        if file_path.exists():
            conflicts['config_files'].append(file_path)
    
    # Check for profile-specific files
    profiles_dir = dest_path / 'profiles'
    if profiles_dir.exists():
        profile_file = profiles_dir / f'{profile}.yaml'
        if profile_file.exists():
            conflicts['profile_files'].append(profile_file)
    
    return conflicts

def preview_operations(conflicts: dict, merge: bool, force: bool, dest_path: Path, profile: str):
    """Show preview of what operations would be performed"""
    console.print("\n[bold yellow]DRY RUN MODE - No files will be modified[/bold yellow]\n")
    
    # Files that would be created
    console.print("[bold green]Files that would be created:[/bold green]")
    console.print(f"  ✓ {dest_path / 'custom-rules.yaml'} (main configuration)")
    console.print(f"  ✓ {dest_path / 'profiles' / f'{profile}.yaml'} (profile configuration)")
    
    # Files that would be affected
    if conflicts['config_files'] or conflicts['profile_files']:
        console.print(f"\n[bold yellow]Files that would be {'merged' if merge else 'overwritten'}:[/bold yellow]")
        
        for file_path in conflicts['config_files']:
            status = "📝 would append rules" if merge else "⚠ would overwrite"
            console.print(f"  {status}: {file_path}")
        
        for file_path in conflicts['profile_files']:
            status = "📝 would append rules" if merge else "⚠ would overwrite"
            console.print(f"  {status}: {file_path}")
    
    # Show recommendations
    console.print(f"\n[bold blue]Recommendations:[/bold blue]")
    if conflicts['config_files'] or conflicts['profile_files']:
        if not force and not merge:
            console.print("  • Run with --force to overwrite existing files")
            console.print("  • Run with --merge to append rules to existing files")
        console.print("  • Create backups of important configuration files")
    
    console.print("  • Review the changes before running without --dry-run")

def run_interactive_setup(dest_path: Path, profile: str, force: bool, merge: bool):
    """Run interactive setup wizard"""
    console.print("\n[bold blue]🚀 Custom Rules Interactive Setup[/bold blue]\n")
    
    # TODO: Implement interactive setup wizard
    console.print("[yellow]Interactive setup will be implemented in the next phase[/yellow]")
    
    # For now, run standard init
    conflicts = analyze_existing_files(dest_path, profile)
    run_standard_init(conflicts, force, merge, dest_path, profile)

def run_standard_init(conflicts: dict, force: bool, merge: bool, dest_path: Path, profile: str):
    """Run standard initialization"""
    
    # Handle conflicts
    if conflicts['config_files'] or conflicts['profile_files']:
        if not force and not merge:
            console.print("[yellow]⚠ Existing configuration files detected:[/yellow]")
            for file_path in conflicts['config_files'] + conflicts['profile_files']:
                console.print(f"  • {file_path}")
            
            if not Confirm.ask("\nDo you want to overwrite these files?", default=False):
                console.print("[yellow]Initialization cancelled by user[/yellow]")
                return
            force = True
    
    # Create directories
    dest_path.mkdir(parents=True, exist_ok=True)
    profiles_dir = dest_path / 'profiles'
    profiles_dir.mkdir(exist_ok=True)
    
    # Create main configuration
    create_main_config(dest_path, force, merge)
    
    # Create profile configuration
    create_profile_config(profiles_dir / f'{profile}.yaml', profile, force, merge)

def create_main_config(dest_path: Path, force: bool, merge: bool):
    """Create main configuration file"""
    config_path = dest_path / 'custom-rules.yaml'
    
    config_content = """# Generated by Copilot
# Custom Rules Main Configuration
name: "custom-rules-config"
version: "1.0.0"

# Global settings
settings:
  output_format: "json"
  verbose: false
  max_workers: 4
  backup_enabled: true

# Default rules
rules:
  - name: "file-permissions"
    description: "Check file permissions"
    enabled: true
    severity: "warning"
    
  - name: "naming-convention"
    description: "Validate naming conventions"
    enabled: true
    severity: "error"
    
  - name: "code-quality"
    description: "Basic code quality checks"
    enabled: false
    severity: "info"

# Output destinations
destinations:
  reports: "./reports"
  logs: "./logs"
  backups: "./backups"

# Integration settings
integrations:
  git:
    enabled: false
    hooks: []
  ci_cd:
    enabled: false
"""
    
    if merge and config_path.exists():
        # TODO: Implement merge logic
        console.print(f"[yellow]Merge functionality will be implemented in next phase[/yellow]")
    
    with open(config_path, 'w', encoding='utf-8') as f:
        f.write(config_content)
    
    console.print(f"[green]✓ Created main configuration: {config_path}[/green]")

def create_profile_config(profile_path: Path, profile_name: str, force: bool, merge: bool):
    """Create profile-specific configuration"""
    
    profile_content = f"""# Generated by Copilot
# Custom Rules Profile: {profile_name}
name: "{profile_name}"
description: "Configuration profile for {profile_name} environment"
extends: "base"

# Profile-specific settings
settings:
  environment: "{profile_name}"
  strict_mode: {'true' if profile_name == 'production' else 'false'}
  
# Profile-specific rules
rules:
  - name: "env-specific-check"
    description: "Environment-specific validation"
    enabled: true
    config:
      environment: "{profile_name}"
      
# Profile destinations
destinations:
  reports: "./reports/{profile_name}"
  logs: "./logs/{profile_name}"
"""
    
    if merge and profile_path.exists():
        # TODO: Implement merge logic
        console.print(f"[yellow]Merge functionality will be implemented in next phase[/yellow]")
    
    with open(profile_path, 'w', encoding='utf-8') as f:
        f.write(profile_content)
    
    console.print(f"[green]✓ Created profile configuration: {profile_path}[/green]")
