# Generated by Copilot
"""
Profile management commands for Custom Rules CLI
"""
import click
from pathlib import Path
from rich.console import Console
from rich.table import Table
import yaml

console = Console()

@click.group()
def profile_group():
    """Manage configuration profiles"""
    pass

@profile_group.command()
@click.pass_context
def list(ctx):
    """List available profiles"""
    profiles_dir = Path.cwd() / 'profiles'
    
    if not profiles_dir.exists():
        console.print("[yellow]No profiles directory found. Run 'custom-rules init' first.[/yellow]")
        return
    
    profile_files = list(profiles_dir.glob('*.yaml')) + list(profiles_dir.glob('*.yml'))
    
    if not profile_files:
        console.print("[yellow]No profiles found in profiles directory.[/yellow]")
        return
    
    table = Table(title="Available Profiles")
    table.add_column("Name", style="cyan")
    table.add_column("Description", style="green")
    table.add_column("File", style="dim")
    
    for profile_file in sorted(profile_files):
        try:
            with open(profile_file, 'r', encoding='utf-8') as f:
                profile_data = yaml.safe_load(f) or {}
            
            name = profile_data.get('name', profile_file.stem)
            description = profile_data.get('description', 'No description')
            
            table.add_row(name, description, str(profile_file.name))
        except Exception as e:
            table.add_row(profile_file.stem, f"[red]Error loading: {e}[/red]", str(profile_file.name))
    
    console.print(table)

@profile_group.command()
@click.argument('name')
@click.option('--interactive', '-i', is_flag=True, help='Create profile interactively')
@click.pass_context
def create(ctx, name, interactive):
    """Create a new profile"""
    profiles_dir = Path.cwd() / 'profiles'
    profiles_dir.mkdir(exist_ok=True)
    
    profile_path = profiles_dir / f'{name}.yaml'
    
    if profile_path.exists():
        console.print(f"[yellow]Profile '{name}' already exists at {profile_path}[/yellow]")
        return
    
    if interactive:
        console.print("[yellow]Interactive profile creation will be implemented in next phase[/yellow]")
    
    # Create basic profile template
    profile_content = f"""# Generated by Copilot
name: "{name}"
description: "Custom profile: {name}"
version: "1.0.0"

settings:
  environment: "{name}"
  verbose: false
  
rules: []

destinations:
  reports: "./reports/{name}"
  logs: "./logs/{name}"
"""
    
    with open(profile_path, 'w', encoding='utf-8') as f:
        f.write(profile_content)
    
    console.print(f"[green]✓ Created profile '{name}' at {profile_path}[/green]")

@profile_group.command()
@click.argument('name')
@click.pass_context
def delete(ctx, name):
    """Delete a profile"""
    profiles_dir = Path.cwd() / 'profiles'
    profile_path = profiles_dir / f'{name}.yaml'
    
    if not profile_path.exists():
        console.print(f"[yellow]Profile '{name}' not found[/yellow]")
        return
    
    if click.confirm(f"Delete profile '{name}'?"):
        profile_path.unlink()
        console.print(f"[green]✓ Deleted profile '{name}'[/green]")
    else:
        console.print("[yellow]Deletion cancelled[/yellow]")

@profile_group.command()
@click.argument('name')
@click.pass_context
def show(ctx, name):
    """Show profile details"""
    profiles_dir = Path.cwd() / 'profiles'
    profile_path = profiles_dir / f'{name}.yaml'
    
    if not profile_path.exists():
        console.print(f"[yellow]Profile '{name}' not found[/yellow]")
        return
    
    try:
        with open(profile_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        console.print(f"[bold blue]Profile: {name}[/bold blue]")
        console.print(f"[dim]File: {profile_path}[/dim]\n")
        console.print(content)
    except Exception as e:
        console.print(f"[red]Error reading profile: {e}[/red]")
