// Generated by Copilot
import { SecurityValidator } from '../../utils/security.js';
import { ConfigSchema } from '../../core/config.js';

describe('SecurityValidator', () => {
  let validator: SecurityValidator;
  let testConfig: ConfigSchema;

  beforeEach(() => {
    testConfig = {
      name: 'test',
      version: '1.0.0',
      settings: {
        output_format: 'json',
        verbose: false
      },
      rules: [],
      destinations: {
        reports: './reports',
        logs: './logs'
      },
      security: {
        neverExecute: [
          'rm -rf /',
          'del /f /s /q C:\\*',
          'format c:',
          'shutdown'
        ],
        blockedCommands: [
          'sudo *',
          'curl *://*/malware*'
        ],
        unsafePatterns: [
          '\\$\\([^)]*\\)',
          '`[^`]*`'
        ]
      },
      exclusions: {
        files: ['.env', '*.key'],
        directories: ['node_modules', '.git'],
        patterns: ['**/node_modules/**', '**/*.log'],
        extensions: ['.exe', '.bat']
      },
      integrations: {
        git: {
          enabled: false
        }
      }
    };

    validator = new SecurityValidator(testConfig);
  });

  describe('Command Validation', () => {
    it('should block never-execute commands', () => {
      const result = validator.validateCommand('rm -rf /');
      
      expect(result.isAllowed).toBe(false);
      expect(result.riskLevel).toBe('critical');
      expect(result.reason).toContain('blocked pattern');
    });

    it('should block dangerous commands', () => {
      const result = validator.validateCommand('sudo rm -rf /home');
      
      expect(result.isAllowed).toBe(false);
      expect(result.riskLevel).toBe('high');
    });

    it('should detect unsafe patterns', () => {
      const result = validator.validateCommand('echo $(cat /etc/passwd)');
      
      expect(result.isAllowed).toBe(false);
      expect(result.riskLevel).toBe('medium');
    });

    it('should allow safe commands', () => {
      const result = validator.validateCommand('npm test');
      
      expect(result.isAllowed).toBe(true);
      expect(result.riskLevel).toBe('low');
    });

    it('should handle case-insensitive matching', () => {
      const result = validator.validateCommand('RM -RF /');
      
      expect(result.isAllowed).toBe(false);
      expect(result.riskLevel).toBe('critical');
    });
  });

  describe('File Exclusion', () => {
    it('should exclude specific files', () => {
      expect(validator.shouldExcludeFile('.env')).toBe(true);
      expect(validator.shouldExcludeFile('secret.key')).toBe(true);
    });

    it('should exclude by extension', () => {
      expect(validator.shouldExcludeFile('malware.exe')).toBe(true);
      expect(validator.shouldExcludeFile('script.bat')).toBe(true);
    });

    it('should exclude directories', () => {
      expect(validator.shouldExcludeFile('node_modules/package/index.js')).toBe(true);
      expect(validator.shouldExcludeFile('.git/config')).toBe(true);
    });

    it('should exclude by patterns', () => {
      expect(validator.shouldExcludeFile('path/to/node_modules/file.js')).toBe(true);
      expect(validator.shouldExcludeFile('debug.log')).toBe(true);
    });

    it('should allow normal files', () => {
      expect(validator.shouldExcludeFile('src/index.ts')).toBe(false);
      expect(validator.shouldExcludeFile('README.md')).toBe(false);
    });
  });

  describe('Summary Functions', () => {
    it('should provide security summary', () => {
      const summary = validator.getSecuritySummary();
      
      expect(summary.neverExecute).toHaveLength(4);
      expect(summary.blockedCommands).toHaveLength(2);
      expect(summary.unsafePatterns).toHaveLength(2);
    });

    it('should provide exclusion summary', () => {
      const summary = validator.getExclusionSummary();
      
      expect(summary.files).toHaveLength(2);
      expect(summary.directories).toHaveLength(2);
      expect(summary.patterns).toHaveLength(2);
      expect(summary.extensions).toHaveLength(2);
    });
  });
});
